// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP_SthwiCVUBp-3E6JS7RkEfVGVm6G15k',
    appId: '1:693814568314:web:22be303ff1481ddcd7e2c3',
    messagingSenderId: '693814568314',
    projectId: 'scholarchat-123',
    authDomain: 'scholarchat-123.firebaseapp.com',
    storageBucket: 'scholarchat-123.firebasestorage.app',
    measurementId: 'G-Y2M2R416JJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOkz9Uz8YhkqCBRZew8hE8sq1WTBbhYIE',
    appId: '1:693814568314:android:44455eca2414a5edd7e2c3',
    messagingSenderId: '693814568314',
    projectId: 'scholarchat-123',
    storageBucket: 'scholarchat-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU7qSzDXXArlnTiwr1zBsofQ_qKq7V6OQ',
    appId: '1:693814568314:ios:57efc992c55002c4d7e2c3',
    messagingSenderId: '693814568314',
    projectId: 'scholarchat-123',
    storageBucket: 'scholarchat-123.firebasestorage.app',
    iosBundleId: 'com.example.scholarChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU7qSzDXXArlnTiwr1zBsofQ_qKq7V6OQ',
    appId: '1:693814568314:ios:57efc992c55002c4d7e2c3',
    messagingSenderId: '693814568314',
    projectId: 'scholarchat-123',
    storageBucket: 'scholarchat-123.firebasestorage.app',
    iosBundleId: 'com.example.scholarChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP_SthwiCVUBp-3E6JS7RkEfVGVm6G15k',
    appId: '1:693814568314:web:15e381116fa69d4dd7e2c3',
    messagingSenderId: '693814568314',
    projectId: 'scholarchat-123',
    authDomain: 'scholarchat-123.firebaseapp.com',
    storageBucket: 'scholarchat-123.firebasestorage.app',
    measurementId: 'G-BJMPF2V3ZX',
  );
}
